/** Frases para completar. El hueco se marca con "___". */
export const PHRASES: string[] = [
  'Lo peor que te pueden decir en un primer date es ___.',
  'Mi plan infalible para no ir a laburar: ___.',
  'Nunca confíes en alguien que ___.',
  'El verdadero motivo por el que se extinguieron los dinosaurios fue ___.',
  'En mi funeral quiero que suene ___.',
  'Si fuera presidente, lo primero que prohibiría sería ___.',
  'La peor forma de terminar una relación es con un mensaje que diga ___.',
  'Mi superpoder más inútil sería ___.',
  'Lo que realmente pasa cuando apagás la luz de la heladera es ___.',
  'El nuevo deporte olímpico debería ser ___.',
  'La excusa más barata para llegar tarde: ___.',
  'Si los perros hablaran, lo primero que dirían es ___.',
  'Mi biografía se va a llamar ___.',
  'Nada arruina más un asado que ___.',
  'Lo que encontré en el fondo de mi mochila fue ___.',
  'El peor regalo para el amigo invisible es ___.',
  'En el futuro, los chicos no van a entender qué era ___.',
  'Mi tatuaje de arrepentimiento dice ___.',
  'El sonido más molesto del universo es ___.',
  'Si me sobran dos pesos me compro ___.',
  'La contraseña de mi ex seguro era ___.',
  'Lo único que me mantiene cuerdo es ___.',
  'El peor consejo que me dieron fue ___.',
  'Después de medianoche, mi cocina se transforma en ___.',
  'Si me encuentro un genio de la lámpara, le pido ___.',
  'El mejor insulto que inventé es ___.',
  'Mi versión de "tocar fondo" es ___.',
  'Lo más caro que rompí sin querer fue ___.',
  'La peor idea de negocio del mundo: ___.',
  'Mi grupo de WhatsApp más tóxico se llama ___.',
  'El cartel que pondría en la puerta de mi casa dice ___.',
  'Lo que hago cuando nadie me ve es ___.',
  'La comida que me reconcilia con la vida es ___.',
  'Si me persigue un oso, mi estrategia es ___.',
  'Mi mayor logro del año fue ___.',
  'El peor nombre posible para un bebé es ___.',
  'En mi lápida quiero que diga ___.',
  'La verdadera razón por la que no contesto el teléfono es ___.',
  'El sabor de helado que nadie pidió: ___.',
  'Lo que gritaría desde la terraza a las 3 de la mañana: ___.',
  'Mi talento oculto es ___.',
  'La peor película jamás hecha se llamaría ___.',
  'Si tuviera que vivir de un solo plato sería ___.',
  'Lo que me da más vergüenza ajena es ___.',
  'El invento que el mundo necesita urgente es ___.',
  'Lo que diría un alien al aterrizar acá: ___.',
  'Mi mayor miedo irracional es ___.',
  'El trabajo soñado para alguien sin vergüenza es ___.',
  'Lo que pasa realmente en los grupos de padres del colegio es ___.',
  'Si la vida tuviera botón de deshacer, lo usaría para ___.',
  'El peor momento para que te suene el teléfono es ___.',
  'Mi animal espiritual es ___.',
  'La frase que más odio escuchar es ___.',
  'Lo que escondo cuando vienen visitas es ___.',
  'El examen final de la vida adulta debería evaluar ___.',
  'Mi horóscopo de hoy dice ___.',
  'El peor souvenir que traje de un viaje fue ___.',
  'Nunca llegué tan rápido a ningún lado como cuando ___.',
  'Si me dan un micrófono abierto, digo ___.',
  'El villano más subestimado de la historia es ___.',
  'Lo primero que haría con un millón de dólares es ___.',
  'La peor manera de despertarse es con ___.',
  'Mi relación con el gimnasio se puede describir como ___.',
  'El emoji que me representa es ___.',
  'Lo que nunca voy a perdonar es ___.',
];
