/** Palabras y frases para Vicente van Gogh. `hint` es la categoría que se muestra. */
export interface WordEntry {
  word: string;
  hint: string;
}

export const WORDS: WordEntry[] = [
  // Objetos cotidianos
  { word: 'un mate con termo', hint: 'Objeto' },
  { word: 'un paraguas roto', hint: 'Objeto' },
  { word: 'una heladera abierta', hint: 'Objeto' },
  { word: 'un control remoto', hint: 'Objeto' },
  { word: 'una bicicleta sin rueda', hint: 'Objeto' },
  { word: 'un despertador', hint: 'Objeto' },
  { word: 'una tostadora', hint: 'Objeto' },
  { word: 'un ventilador de techo', hint: 'Objeto' },
  { word: 'una lámpara de lava', hint: 'Objeto' },
  { word: 'un carrito de supermercado', hint: 'Objeto' },
  { word: 'una máquina de escribir', hint: 'Objeto' },
  { word: 'un teléfono con cable', hint: 'Objeto' },
  { word: 'una pecera', hint: 'Objeto' },
  { word: 'un semáforo', hint: 'Objeto' },
  { word: 'una guitarra eléctrica', hint: 'Objeto' },

  // Animales
  { word: 'un pingüino con bufanda', hint: 'Animal' },
  { word: 'un pulpo bailando', hint: 'Animal' },
  { word: 'una vaca en la playa', hint: 'Animal' },
  { word: 'un gato manejando', hint: 'Animal' },
  { word: 'un dinosaurio chiquito', hint: 'Animal' },
  { word: 'un caracol apurado', hint: 'Animal' },
  { word: 'un cocodrilo sonriendo', hint: 'Animal' },
  { word: 'una jirafa con sombrero', hint: 'Animal' },
  { word: 'un perro salchicha', hint: 'Animal' },
  { word: 'un mono comiendo helado', hint: 'Animal' },
  { word: 'una abeja enojada', hint: 'Animal' },
  { word: 'un elefante en patines', hint: 'Animal' },
  { word: 'un tiburón vegetariano', hint: 'Animal' },
  { word: 'una tortuga ninja', hint: 'Animal' },
  { word: 'un flamenco dormido', hint: 'Animal' },

  // Comida
  { word: 'un asado completo', hint: 'Comida' },
  { word: 'una pizza voladora', hint: 'Comida' },
  { word: 'un alfajor mordido', hint: 'Comida' },
  { word: 'milanesa con papas', hint: 'Comida' },
  { word: 'una empanada gigante', hint: 'Comida' },
  { word: 'un choripán', hint: 'Comida' },
  { word: 'un helado derritiéndose', hint: 'Comida' },
  { word: 'sushi mal hecho', hint: 'Comida' },
  { word: 'un flan con dulce de leche', hint: 'Comida' },
  { word: 'una sandía cuadrada', hint: 'Comida' },
  { word: 'panqueques apilados', hint: 'Comida' },
  { word: 'un fernet con coca', hint: 'Comida' },

  // Lugares y escenas
  { word: 'un atardecer en la playa', hint: 'Lugar' },
  { word: 'el subte en hora pico', hint: 'Lugar' },
  { word: 'una isla desierta', hint: 'Lugar' },
  { word: 'un castillo embrujado', hint: 'Lugar' },
  { word: 'el obelisco', hint: 'Lugar' },
  { word: 'una cancha de fútbol llena', hint: 'Lugar' },
  { word: 'un bosque de noche', hint: 'Lugar' },
  { word: 'la luna con una bandera', hint: 'Lugar' },
  { word: 'un embotellamiento', hint: 'Lugar' },
  { word: 'una ciudad bajo el agua', hint: 'Lugar' },
  { word: 'un parque de diversiones', hint: 'Lugar' },
  { word: 'una estación espacial', hint: 'Lugar' },

  // Acciones y situaciones
  { word: 'alguien resbalando con una banana', hint: 'Situación' },
  { word: 'un robo fallido', hint: 'Situación' },
  { word: 'una propuesta de casamiento', hint: 'Situación' },
  { word: 'perder el colectivo', hint: 'Situación' },
  { word: 'cortar el pasto', hint: 'Situación' },
  { word: 'una pelea de almohadas', hint: 'Situación' },
  { word: 'un penal errado', hint: 'Situación' },
  { word: 'desenchufar el wifi', hint: 'Situación' },
  { word: 'quedarse dormido en clase', hint: 'Situación' },
  { word: 'bailar con dos pies izquierdos', hint: 'Situación' },
  { word: 'armar un mueble sin instrucciones', hint: 'Situación' },
  { word: 'sacarse una selfie con un oso', hint: 'Situación' },

  // Fantasía
  { word: 'un dragón resfriado', hint: 'Fantasía' },
  { word: 'un robot enamorado', hint: 'Fantasía' },
  { word: 'un fantasma tímido', hint: 'Fantasía' },
  { word: 'un unicornio punk', hint: 'Fantasía' },
  { word: 'un alien haciendo compras', hint: 'Fantasía' },
  { word: 'un mago sin varita', hint: 'Fantasía' },
  { word: 'una sirena con patines', hint: 'Fantasía' },
  { word: 'un zombie corriendo una maratón', hint: 'Fantasía' },
  { word: 'un vampiro tomando sol', hint: 'Fantasía' },
  { word: 'un yeti en el desierto', hint: 'Fantasía' },
  { word: 'un superhéroe jubilado', hint: 'Fantasía' },
  { word: 'un pirata sin barco', hint: 'Fantasía' },

  // Conceptos abstractos (los difíciles)
  { word: 'la nostalgia', hint: 'Abstracto' },
  { word: 'el lunes a la mañana', hint: 'Abstracto' },
  { word: 'la gravedad', hint: 'Abstracto' },
  { word: 'el silencio', hint: 'Abstracto' },
  { word: 'la inflación', hint: 'Abstracto' },
  { word: 'un déjà vu', hint: 'Abstracto' },
  { word: 'la suerte', hint: 'Abstracto' },
  { word: 'el aburrimiento', hint: 'Abstracto' },
  { word: 'la amistad', hint: 'Abstracto' },
  { word: 'el pánico', hint: 'Abstracto' },
  { word: 'la paciencia', hint: 'Abstracto' },
  { word: 'el caos', hint: 'Abstracto' },

  // Profesiones y personajes
  { word: 'un astronauta jardinero', hint: 'Personaje' },
  { word: 'un chef desesperado', hint: 'Personaje' },
  { word: 'un payaso triste', hint: 'Personaje' },
  { word: 'un detective con lupa', hint: 'Personaje' },
  { word: 'un bombero gato', hint: 'Personaje' },
  { word: 'un dj en una fiesta vacía', hint: 'Personaje' },
  { word: 'un cartero perdido', hint: 'Personaje' },
  { word: 'un boxeador cansado', hint: 'Personaje' },
  { word: 'una bibliotecaria furiosa', hint: 'Personaje' },
  { word: 'un taxista filósofo', hint: 'Personaje' },

  // Random divertido
  { word: 'una tostada con cara', hint: 'Random' },
  { word: 'el sol con anteojos', hint: 'Random' },
  { word: 'una nube con lluvia de peces', hint: 'Random' },
  { word: 'un árbol con ruedas', hint: 'Random' },
  { word: 'una escalera infinita', hint: 'Random' },
  { word: 'un reloj derretido', hint: 'Random' },
  { word: 'zapatillas con alas', hint: 'Random' },
  { word: 'una montaña rusa rota', hint: 'Random' },
  { word: 'un globo aerostático', hint: 'Random' },
  { word: 'una estatua haciendo gimnasia', hint: 'Random' },
  { word: 'un volcán de chocolate', hint: 'Random' },
  { word: 'una casa patas para arriba', hint: 'Random' },
  { word: 'un arcoíris torcido', hint: 'Random' },
  { word: 'un cactus con flores', hint: 'Random' },
  { word: 'una isla flotante', hint: 'Random' },
];
